name: Build and Deploy Rust Webserver

on:
  push:
    branches:
      - release  # Trigger only on pushes to release branch

jobs:
  build-and-deploy:
    runs-on: webserver_runner  # your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test

      - name: Build release binary
        run: cargo build --release

      - name: Deploy binary
        run: |
          sudo systemctl stop rust_webserver
          sudo cp target/release/rust_webserver /root/webserver/rust_webserver
          sudo systemctl start rust_webserver
      
      - name: Cleanup
        if: always()
        run: cargo clean

