name: Build and Deploy Rust Webserver

on:
  push:
    branches:
      - release  # Trigger only on pushes to release branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binaryD
        run: cargo build --release

      - name: Deploy binary
        run: |
          mkdir -p ~/bin
          cp target/release/rust_webserver /root/webserver/rust_webserver
          # Stop old instance
          pkill -f rust_webserver || true
          # Start in background
          sudo systemctl restart rust_webserver
          
      
